# Generated by Django 5.0.6 on 2024-05-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_no_of_copies_borrowedlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedlist',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
