# Generated by Django 5.0.6 on 2024-05-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_borrowedlist_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
